// Code generated by go generate; DO NOT EDIT.
// This file was generated on {{.DateTime}}
// using data from https://www.alphavantage.co/documentation

package alphavantage

func (av *Alphavantage) GetOverview() {
	av.client.Hello()
}

// Checksum: C9nQYlBo4vIrBxhXXTFbZct/xYtP+sCm209jYlnOhao=
